% Sun Jul 27 18:01:21 WIB 2014
% Karl Kastner, Berlin

function gpx_export_csv(gpx,filename)

	fid = fopen(filename,'w');

	if (-1 == fid)
		error(['Cannot open file ', filename, ' for writing ']);
	end

	[t,sdx] = sort(gpx.time);
	t       = gpx.time;
	fprintf(fid,'Lat;Lon;X;Y;Z;Date;Time;TimeStr;Name;Comment;MTime\n');
	for idx=1:length(t)
		fprintf(fid,'%f;%f;%f;%f;%f;''%s'';''%s'';''%s'';''%s'';''%s'';%f\n', ...
                           gpx.lat(sdx(idx)), ...
			   gpx.lon(sdx(idx)), ...
                           gpx.X(sdx(idx)), ...
                           gpx.Y(sdx(idx)), ...
                           gpx.ele(sdx(idx)), ...
			   datestr(t(sdx(idx)),'dd/mm/yyyy'), ...
			   datestr(t(sdx(idx)),'HH:MM:SS'), ...
			   gpx.timestr{sdx(idx)}, ...
                           gpx.name{sdx(idx)}, ...
                           gpx.cmt{sdx(idx)}, ...
			   t(idx));
	end % for idx
end

